# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

use_frameworks!

target 'Expenses' do 
	
end

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
  
